POST http://localhost:3306/user/create
Content-Type: application/json

{
    "name": "teste",
    "email": "email@email.com",
    "password": "23432535"
}

###
GET http://localhost:3306/user
Content-Type: application/json

###
POST http://localhost:3306/movie
Content-Type: application/json

{
    "title": "Era Uma Vez",
    "description": "Muito bom!",
    "durationInMinutes": "120",
    "yearOfRelease": "2001"
}

